apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}
  namespace: {{ .Release.Namespace }} # picked up from Skaffold yaml
  labels:
    app: {{.Values.app.name}}
spec:
  selector:
    app.kubernetes.io/name: {{.Values.app.name}}
    # app.kubernetes.io/name: ingress-nginx
    # app.kubernetes.io/part-of: ingress-nginx
  type: LoadBalancer
  ports:

    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21

    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22

    - name: telnet
      protocol: TCP
      port: 23
      targetPort: 23

    - name: smb 
      protocol: TCP
      port: 445
      targetPort: 445

    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306

    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432

    - name: vnc
      protocol: TCP
      port: 5900
      targetPort: 5900

    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379

    - name: elastic
      protocol: TCP
      port: 9200
      targetPort: 9200

    # - name: xxx
    #   protocol: TCP
    #   port: 1111
    #   targetPort: 1111
