apiVersion: v1
kind: ConfigMap
data:
  # https://minikube.sigs.k8s.io/docs/tutorials/nginx_tcp_udp_ingress/
  # port: namespace/service:port
  21: "honeypots/honeypots:21"
  22: "honeypots/honeypots:22"
  23: "honeypots/honeypots:23"
  445: "honeypots/honeypots:445"
  3306: "honeypots/honeypots:3306"
  5432: "honeypots/honeypots:5432"
  5900: "honeypots/honeypots:5900"
  6379: "honeypots/honeypots:6379"
  9200: "honeypots/honeypots:9200"
  #21: "honeypots/honeypots:21"
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: tcp-services
  namespace: ingress-nginx